### ISSUE TITLE
Using with drone connected to other wifi (and different IP)

### ISSUE THREAD

**Issue by bryceadams** [jolicode/php-ar-drone#5]
Hi! I've got a drone setup connected to a secured network, using https://github.com/daraosn/ardrone-wpa2

The IP it's using is `192.168.1.107`. I had to manually change this in the Config class (as there doesn't seem to be an option for this like with node-ar-drone.

That doesn't seem to the trick though and I still can't execute any commands.

Have you had success doing this and using the php-ar-drone library?

It works with node-ar-drone setup like this, so I'm not sure what could be the issue.

Cheers!

**Comment by lyrixx** [comment]
Hello. 

Sorry for the very long delay here 😅 

Unfortunately, we don't support this repository anymore...
That's why I close this issue.

Sorry
